config/routes.rb
Rails.application.routes.draw do
  root 'url#index'
  post '/url_create' => 'url#create'
  get '/:short' => 'url#show', as: 'short'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'url#index'
  # #
  # # get 'url/show'
  # resources :url
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  def self.random_letters
  all_letters = ('a'..'z').to_a

  return all_letters.sample
  end

  def self.random_string(num_of_letters = 3)
  output = ""

  num_of_letters.times do |char|
    output << self.random_letters
  end
  return output
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/url_controller.rb
class UrlController < ApplicationController
  def index
    @urls = Url.all
    @url = Url.new
  end

  def show
    @url = short_url
    redirect_to @url.name
  end

  def create
    @url = Url.new(url_params)
    @url.short = Url.random_string
    @url.save
    redirect_to root_path

  end
  private

    def url_params
    params.require(:url).permit(:name)
    end

    def short_url
      @url = Url.find_by(short: params[:short])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Url Shortener!</h1>
  <p class="lead">This is a simple App that converts a long Url to a short one.</p>

  <%= form_tag '/url_create' do %>
    <%= text_field(:url, :name, :placeholder=>'Enter your url', :class=>'form-control text-center' ) %>
    <%= submit_tag('Submit', :class=>'btn btn-primary form-control ') %>
  <% end %>
  <br>
  <br>

  <% if @urls.any? %>
    <table class="table table-bordered table-hover">
      <!-- <thead class="table"> -->
      <tr class='table-active'>
        <th>Id</th>
        <th>Original URL</th>
        <th>Shortened URL</th>
      </tr>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.id %> </td>
        <td><%= url.name %> </td>
        <td>
          <%= link_to url.short, short_path(short: url.short), target: :_blank %>
        </td>
      </tr>
    <% end %>
    </table>
  <% else %>
     <p>No shortened urls yet.</p>
  <% end %>



</div>






<!-- <h1 style="text-align:center">Url Address</h1> -->

app/views/url/show.html.erb
<h1>Url#show</h1>